[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "eval-data-gen-lib"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
eval-data-gen = "eval_data_gen.cli.main:app"
